"""rename department

Revision ID: 37b9c5d6d9cc
Revises: 41bbd7af1148
Create Date: 2024-10-02 09:52:02.293791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b9c5d6d9cc'
down_revision = '41bbd7af1148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    op.drop_table('departments')
    # ### end Alembic commands ###
