"""rename address

Revision ID: 4862674f3212
Revises: 37b9c5d6d9cc
Create Date: 2024-10-02 09:55:35.158512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4862674f3212'
down_revision = '37b9c5d6d9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###